export * from "./arr/augmented";
export * from "./cont/augmented";
export * from "./genericeithert/augmented";
export * from "./either/augmented";
export * from "./fn/augmented";
export * from "./fnctr/augmented";
export * from "./genericlist/augmented";
export * from "./int/augmented";
export * from "./iter/augmented";
import * as Maybe from "./maybe";
export { Maybe };
export * from "./obj/augmented";
export * from "./prm/augmented";
export * from "./readert/augmented";
export * from "./statet/augmented";
import * as Str from "./str";
export { Str };
import * as Unit from "./unit";
export { Unit };
export * from "./misc";
import * as Lens from "./lens";
export { Lens };
export * from "./kleisli/augmented";
export * from "./vec/augmented";
export * from "./identity/augmented";
